package ar.edu.unlu.mancala.modelo;

public enum Informe {
	LISTOPARACOMENZAR,
	POSICIONINEXISTENTE,
	SIGUIENTEJUGADOR, 
	NOHAYHABAS, 
	JUGADORFUERADEPARAMETRO, 
	CASILLADEOTROJUGADOR, 
	JUEGADENUEVO, 
	JUEGOFINALIZADO,
}
